export const ROUTE_HOME = 'routesMap/ROUTE_HOME'
export const ROUTE_ORGS = 'routesMap/ROUTE_ORGS'
export const ROUTE_ORG_REPOS = 'routesMap/ROUTE_ORG_REPOS'
export const ROUTE_LOAD = 'routesMap/ROUTE_LOAD'
export const ROUTE_EDIT = 'routesMap/ROUTE_EDIT'
export const ROUTE_MODELS = 'routesMap/ROUTE_MODELS'
export const ROUTE_MODEL_EDIT = 'routesMap/ROUTE_MODEL_EDIT'
export const ROUTE_IMAGES = 'routesMap/ROUTE_IMAGES'
export const ROUTE_IMAGE_EDIT = 'routesMap/ROUTE_IMAGE_EDIT'
export const ROUTE_SOUNDS = 'routesMap/ROUTE_SOUNDS'
export const ROUTE_SOUND_EDIT = 'routesMap/ROUTE_SOUND_EDIT'
export const ROUTE_MUSICS = 'routesMap/ROUTE_MUSICS'
export const ROUTE_MUSIC_EDIT = 'routesMap/ROUTE_MUSIC_EDIT'

export const isRouteAction = (action) => (action.startsWith('routesMap/'))
